language: c

cache:
  directories:
    - $HOME/travis-cache

matrix:
  include:
    - env: ENV=OSX
      arch: amd64
      os: osx
    - env: ENV=xenial
      arch: amd64
      dist: xenial
    - env: ENV=bionic
      arch: amd64
      dist: bionic
    - env: ENV=bionic
      arch: ppc64le
      dist: bionic
    - env: ENV=xenial
      arch: ppc64le
      dist: xenial
    - env: ENV=bionic
      arch: arm64
      dist: bionic
    - env: ENV=xenial
      arch: arm64
      dist: xenial
    - env: ENV=bionic
      arch: s390x
      dist: bionic
    - env: ENV=xenial
      arch: s390x
      dist: xenial

compiler:
  - gcc
  - clang

script: ci/arm64-segfault-demo.sh

notifications:
  email: false
