language: c

cache:
  directories:
    - $HOME/travis-cache

matrix:
  include:
    - arch: amd64
      os: osx
    - arch: amd64
      dist: xenial
    - arch: amd64
      dist: bionic
    - arch: ppc64le
      dist: bionic
    - arch: ppc64le
      dist: xenial
    - arch: arm64
      dist: bionic
    - arch: arm64
      dist: xenial
    - arch: s390x
      dist: bionic
    - arch: s390x
      dist: xenial

compiler:
  - gcc
  - clang

script: ci/arm64-segfault-demo.sh

notifications:
  email: false
